// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: System.CLSCompliant(false)]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangeSpot(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddParkolo(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddParkolas(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.DeleteParkolo(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddCar(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangeSpotSize(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.GetBySpotId(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ListAllSzemely(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddPerson(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.DeletePerson(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangePersonName(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Dont know hos to solve>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.GetByPersonId(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ListAllParkolas(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.GetByRendszam(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddParkolas(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddParkolo(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.DeleteParkolo(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ListAllParkolo(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangeSpotSize(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.GetByPersonId(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangePersonName(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.DeletePerson(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddPerson(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.GetByPlateNum(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ListAllSzemely(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangeFuel(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.AddCar(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.PeopleAndFees(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.DeleteCar(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ListAllAuto(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.GetBySpotId(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.DeleteParkolas(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ChangeSpot(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.UsedSpots(Parkolo.Logic.CarLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.MalePeople(Parkolo.Logic.ParkolasLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Not important>", Scope = "member", Target = "~M:Parkolo.Program.MainProgram.ParkingFeeByVehicle(Parkolo.Logic.CarLogic)")]
